### ISSUE TITLE
gen not working

### ISSUE THREAD

**Issue by gedw99** [medelman17/apollo-studio-client-go#1]
generate -v ./... && go run . is not regenerating the generated.go.

not sure why...

I have installed github.com:Khan/genqlient@v0.5.0, which matches your version in mod.go.

**Comment by medelman17** [comment]
Hi! I'm archiving this repo in favor of https://github.com/apollosolutions/terraform-provider-apollosolutions -- still a work in progress (my Go chops are, erm, rusty...), but the above should work a lot better.
